/* Bot Created and Generated by DISCORD DSL */
/* ======================================== */
/*                                            
Setup Instructions: Verify that you have Node.js installed on your computer. If not, download and install it from the official Node.js website.
Also verify that you have entered the correct TOKEN, CLIENT_ID, and GUILD_ID keys below. They can be found in the Discord Developer Portal.
Additionally, ensure that you have invited the bot onto your discord server and given it the necessary permissions needed
such as the ability to send messages, read messages, and view channels. Also ensure that the bot has been given the necessary
intents in the Discord Developer Portal. We hope you enjoy using this bot and that it serves you well. 
/* ======================================== */
/*
To run the bot, you need to copy the code from the ./botOutput directory into your desination folder. Once moved, open a terminal and navigate to the folder where the bot is located and run npm init. 
This will install the necessary dependencies for the bot to run. Once the dependencies are installed, run the bot by typing node . into the terminal.
*/
/* ======================================== */

// Require the necessary discord.js classes
const {
	REST,
	Client,
	Events,
	GatewayIntentBits,
	Routes,
	ComponentType,
} = require("discord.js");

// Create a new client instance
const client = new Client({
	intents: [
		GatewayIntentBits.Guilds,
		GatewayIntentBits.GuildMessages,
		GatewayIntentBits.MessageContent,
	],
});

TOKEN =
	"REFACTED";
CLIENT_ID = "REDACTED";
GUILD_ID = "1196895637405446176";
general = "general";

client.once(Events.ClientReady, async (readyClient) => {
	console.log(`Ready! Logged in as ${readyClient.user.tag}`);

	client.channels.cache
		.find((channel) => channel.name === general)
		.send("Bot Starting up");
});

client.on("interactionCreate", async (interaction) => {
	try {
		if (interaction.isChatInputCommand()) {
			// Generated Helpers
			if (interaction.user.bot) {
				return;
			}

			Caller = interaction.user.username;
			triggeredChannel = interaction.channel;
			Channel = interaction.channel.name;
			Message = interaction.message;

			Input = interaction.message.content;

			if (interaction.commandName === "help") {
				console.log("Executing Command: help");
				interaction.reply("Initiating Command: help");
				client.channels.cache
					.find((channel) => channel.name === Channel)
					.send("Here are the commands I know");

				client.channels.cache
					.find((channel) => channel.name === Channel)
					.send("1. /rockpaperscissors for a game of rock paper Scissors");

				client.channels.cache
					.find((channel) => channel.name === Channel)
					.send("2. /help for help with how to interact with me!");

				console.log("Command Finished");
			}
		}
	} catch {
		console.log("Fatal Error Occured in Command");
	}
});
client.on("interactionCreate", async (interaction) => {
	try {
		if (interaction.isChatInputCommand()) {
			// Generated Helpers
			if (interaction.user.bot) {
				return;
			}

			Caller = interaction.user.username;
			triggeredChannel = interaction.channel;
			Channel = interaction.channel.name;
			Message = interaction.message;

			Input = interaction.message.content;

			if (interaction.commandName === "rockpaperscissors") {
				console.log("Executing Command: rockpaperscissors");
				interaction.reply("Initiating Command: rockpaperscissors");
				possible_actions = ["rock", "paper", "scissors"];
				tie = true;
				while (tie) {
					client.channels.cache
						.find((channel) => channel.name === Channel)
						.send("Ready to play? Send your choice below");

					user_choice = await triggeredChannel
						.awaitMessages({
							filter: (response) => {
								return response.author.username === Caller;
							},
							max: 1,
							time: 150_000,
							errors: ["time"],
						})
						.then((collected) => {
							return collected.first().content;
						})
						.catch((err) =>
							console.log(
								"No interactions were collected in the time allocated.",
							),
						);

					bot_choice =
						possible_actions[
							Math.floor(Math.random() * possible_actions.length)
							];

					client.channels.cache
						.find((channel) => channel.name === Channel)
						.send(
							"" +
							Caller +
							" chose " +
							user_choice +
							", and I chose " +
							bot_choice +
							"!",
						);

					if (possible_actions.includes(user_choice)) {
						if (user_choice == bot_choice) {
							client.channels.cache
								.find((channel) => channel.name === Channel)
								.send("It's a tie!");
						} else {
							tie = false;
							if (user_choice == "rock") {
								if (bot_choice == "scissors") {
									client.channels.cache
										.find((channel) => channel.name === Channel)
										.send("Rock smashes scissors! You win!");
								} else {
									client.channels.cache
										.find((channel) => channel.name === Channel)
										.send("Paper covers rock! You lose.");
								}
							}
							if (user_choice == "paper") {
								if (bot_choice == "rock") {
									client.channels.cache
										.find((channel) => channel.name === Channel)
										.send("Paper covers rock! You win!");
								} else {
									client.channels.cache
										.find((channel) => channel.name === Channel)
										.send("Scissors cuts paper! You lose.");
								}
							}
							if (user_choice == "scissors") {
								if (bot_choice == "paper") {
									client.channels.cache
										.find((channel) => channel.name === Channel)
										.send("Scissors cuts paper! You win!");
								} else {
									client.channels.cache
										.find((channel) => channel.name === Channel)
										.send("Rock smashes scissors! You lose.");
								}
							}
						}
					} else {
						client.channels.cache
							.find((channel) => channel.name === Channel)
							.send(
								"You didn't choose Rock, Paper, or Scissors! Lets try again.",
							);
					}
				}
				console.log("Command Finished");
			}
		}
	} catch {
		console.log("Fatal Error Occured in Command");
	}
});
// Create a new REST instance
const rest = new REST({ version: "10" }).setToken(TOKEN);

async function main() {
	const commands = [
		{ name: "help", description: "help Command" },
		{ name: "rockpaperscissors", description: "rockpaperscissors Command" },
	];

	try {
		console.log("Started refreshing application (/) commands.");
		await rest.put(Routes.applicationGuildCommands(CLIENT_ID, GUILD_ID), {
			body: commands,
		});
		client.login(TOKEN);
	} catch (err) {
		console.log(err);
	}
}

main();
